<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;
use think\Db;
use think\response\Json;

class Home extends Controller
{
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */

    public $code;
    public $validate;

    public  function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code=config('code');
    }

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
          checkToken();
    }

    public function index()
    {
        //
        $data=$this->request->get();
        $this->validate=validate('Home');

        if(isset($data["page"])  && !empty($data["page"])){
            $page=$data["page"];
        }else{
            $page=1;
        }
        if(isset($data["limit"])  && !empty($data["limit"])){
            $limit=$data["limit"];
        }else{
            $limit=10;
        }
        $where=[];
        if(isset($data['scity']) && !empty($data['scity'])){
            $where['scity']=$data['scity'];
        }
        if(isset($data["sname"])  && !empty($data["sname"])){
            $where["sname"]=['like','%'.$data["sname"].'%'];
        }

        $result=Db::table('home')->where($where)->paginate($limit,false,['page'=>$page]);
        $homedata=$result->items();
        $total=$result->total();
        if($result){
            return json([
                'code'=>200,
                'msg'=>'民宿查询成功',
                'data'=>$homedata,
                'total'=>$total,

            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'民宿查询失败'
            ]);
        }
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //

        $data=$this->request->post();
         $data['ctime']=time();
        $result=Db::table('home')->insert($data);
        if($result){
            return json([
                'code'=>200,
                'msg'=>'民宿添加成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'民宿添加失败'
            ]);
        }

    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //

       $result= Db::table('home')->where('sid',$id)->find();
        $result['sbanner1']=explode(',',$result['sbanner']);
        if($result){

            return json([
                'code'=>200,
                'msg'=>'数据读取成功',
                'data'=>$result
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'暂无数据',

            ]);
        }
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        $data=$request->put();
        $result=Db::table('home')->where('sid',$id)->update($data);
        if($result){
            return json([
                'code'=>200,
                'msg'=>'数据更新成功',

            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'数据更新失败'
            ]);
        }
        //

    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //

        $result=Db::table('home')->where('sid',$id)->delete();
        if($result){
            return json([
                'code'=>200,
                'msg'=>'删除成功',
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'删除失败'
            ]);
        }


    }
}
